#pragma once
#define OFFSET_GAMERENDERER 0x4DA32C0
#define OFFSET_GAMEMANAGER 0x4EBD3C8
#define OFFSET_NAMEMANAGER 0x4E77AF0
#define OFFSET_NETWORKMANAGER 0x4D96538
#define OFFSET_INTERFACEMANAGER 0x4EBBCC0
#define OFFSET_LOCALPLAYER 0x4EBD3D0
#define OFFSET_GADGETMANAGER 0x4D95538
#define OFFSET_STATUSMANAGER 0x4E7F810
 
#define OFFSET_INTERFACEBASE 0x4DB59B0
#define OFFSET_INTERFACE 0x400
#define OFFSET_INCROSSBASE 0x398
#define OFFSET_INCROSS 0x1C8
 
#define OFFSET_GAMERENDERER_DEREF 0x0
#define OFFSET_GAMERENDERER_ENGINELINK 0x120
#define OFFSET_ENGINELINK_ENGINE 0x230
#define OFFSET_ENGINE_CAMERA 0x40
 
#define OFFSET_CAMERA_VIEWRIGHT 0xB0
#define OFFSET_CAMERA_VIEWUP 0xC0
#define OFFSET_CAMERA_VIEFORWARD 0xD0
#define OFFSET_CAMERA_VIEWTRANSLATION 0xE0
#define OFFSET_CAMERA_VIEWFOVX 0xF0
#define OFFSET_CAMERA_VIEWFOVY 0x104
 
#define OFFSET_GAMEMANAGER_ENTITYLIST 0xB8
 
#define OFFSET_ENTITY 0x8
#define OFFSET_ENTITY_REF 0x20
#define OFFSET_ENTITY_ENTITYINFO 0x18
 
#define OFFSET_ENTITYINFO_MAINCOMPONENT 0xA8
#define OFFSET_MAINCOMPONENT_CHILDCOMPONENT 0x08
#define OFFSET_CHILDCOMPONENT_HEALTH 0x148
 
#define OFFSET_ENTITY_PLAYERINFO 0x2B8
#define OFFSET_ENTITY_PLAYERINFO_DEREF 0x0
 
#define OFFSET_PLAYERINFO_MAINCOMPONENT 0x0
#define OFFSET_PLAYERINFO_TEAMID 0x146
#define OFFSET_PLAYERINFO_NAME 0x178
 
#define OFFSET_ENTITY_POSITION 0x1C0
#define OFFSET_ENTITY_NECK 0x170
#define OFFSET_ENTITY_HEAD 0x180
#define OFFSET_ENTITY_FEET 0x1D0
 
#define OFFSET_WEAPONINFO 0x120
#define OFFSET_ANGLEINGO 0x620
 
#define OFFSET_BONE_LEFT_TOE 0x378
#define OFFSET_BONE_LEFT_ANKLE 0x358
#define OFFSET_BONE_LEFT_KNEE 0x3D8
#define OFFSET_BONE_LEFT_HIP 0x3B8
#define OFFSET_BONE_RIGHT_TOE 0x458
#define OFFSET_BONE_RIGHT_ANKLE 0x438
#define OFFSET_BONE_RIGHT_KNEE 0x4B8
#define OFFSET_BONE_RIGHT_HIP 0x498
#define OFFSET_BONE_LEFT_SHOULDER 0x598
#define OFFSET_BONE_LEFT_LBOW 0x5B8
#define OFFSET_BONE_LEFT_HAND 0x5D8
#define OFFSET_BONE_RIGHT_SHOULDER 0xF78
#define OFFSET_BONE_RIGHT_LBOW 0xF98
#define OFFSET_BONE_RIGHT_HAND 0xFB8
